name: Lint

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'README.*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          substituters = https://cache.nixos.org/ https://emacs-ci.cachix.org https://pre-commit-hooks.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=  emacs-ci.cachix.org-1:B5FVOrxhXXrOL0S+tQ7USrhjMT5iOPH+QN9q0NItom4=

    - run: nix run .#nomake -- org-dog byte-compile-and-load
    - run: nix run .#nomake -- org-dog-embark byte-compile-and-load
    - run: nix run .#nomake -- org-dog-consult byte-compile-and-load
    - run: nix run .#nomake -- org-dog-facade byte-compile-and-load
